name: Post Welcome Comment
on:
  pull_request:
    types: [opened]
# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  # Need `pull-requests: write` to create a pull request
  contents: write
  pull-requests: write
jobs:
  build:
    name: Build Welcome Comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome!"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
