name: Post Welcome Comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Build Welcome Comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome!"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
